name: linters

on:
  - pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools poetry
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction
      - name: Run linters & friends
        run: make lint

  pip-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install poetry
        run: python -m pip install --upgrade pip wheel setuptools poetry
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction
      - name: Analysing the dependencies with pip-audit
        run: make deps-audit
